---
title: "תכנית הוראה מפורטת"
---

## יחידה 1: הברונזה המאוחרת או תקופת אל-עמארנה

```{r}
#| echo: false
#| message: false
#| warning: false
df <- read.csv("data/schedule-unit1.csv", check.names = FALSE)
knitr::kable(df, escape = FALSE, format = "html",
  col.names = c("תאריך", "סוג שיעור", "מצגת", "נושאי השיעור", "קריאה / פעילות", "סרטונים ומדיה"),
  table.attr = 'class="table table-striped table-hover" dir="rtl"')
```

## יחידה 2: עדויות לראשית ישראל

```{r}
#| echo: false
#| message: false
#| warning: false
df <- read.csv("data/schedule-unit2.csv", check.names = FALSE)
knitr::kable(df, escape = FALSE, format = "html",
  col.names = c("תאריך", "סוג שיעור", "מצגת", "נושאי השיעור", "קריאה / פעילות", "סרטונים ומדיה"),
  table.attr = 'class="table table-striped table-hover" dir="rtl"')
```

## יחידה 3: תקופת הברזל - מקרא מול ארכיאולוגיה

```{r}
#| echo: false
#| message: false
#| warning: false
df <- read.csv("data/schedule-unit3.csv", check.names = FALSE)
knitr::kable(df, escape = FALSE, format = "html",
  col.names = c("תאריך", "סוג שיעור", "מצגת", "נושאי השיעור", "קריאה / פעילות", "סרטונים ומדיה"),
  table.attr = 'class="table table-striped table-hover" dir="rtl"')
```
