---
title: "בבליוגרפיה ומקורות"
bibliography: refernces.bib
---


## מקורות מקוונים

-   פרויקט עמארנה: [https://www.amarnaproject.com](https://www.amarnaproject.com/)

-   ירושלים בתעודות אל-עמארנה: [Jerusalem in El Amarna](https://www.bibleodyssey.org/articles/jerusalem-in-the-amarna-letters/)

-   ישראל הקדום (פינקלשטיין): [https://israelfinkelstein.wordpress.com/articles/history-of-ancient-israel](https://israelfinkelstein.wordpress.com/articles/history-of-ancient-israel/)

-   ישראל הקדום (עמיחי מזר): [https://www.biblicalarchaeology.org/scholar/amihai-mazar](https://www.biblicalarchaeology.org/scholar/amihai-mazar/)

-   מוזיאון ישראל, רקע ארכיאולוגי: <https://www.imj.org.il/en/wings/archaeology/archaeology-land-israel>

## המזרח הקדום בתקופת הברונזה המאוחרת

1.  @bvnymvbyts2019Prq, [קישור למאמר](https://drive.google.com/file/d/1E-N0fZiNxMwwJfj60Y-OejHp4ZMEUEho/view?usp=sharing){target="_blank"}

2.  @sherratt2013Introduction

3.  @mazar1992Archaeology

4.  @manning2023Severe

## האימפריה המצרית בכנען – תעודות אל-עמארנה

1.  @qvk2018Tslh

2.  @kvkby-ryyny2005

3.  @naaman2005Economic

4.  @koch2021Colonial (מבט ״מלמטה״ על השלטון המצרי)

## עדויות לראשית ישראל – תעודות מהלבנט וממצרים

1.  @kahn2012Merneptah

2.  @cohen2018Cuneiform

## עדויות לראשית ישראל – מקורות מקראיים

1.  @nmn1990Prsht

2.  @naaman2017Rediscovering

## עדויות לראשית ישראל – ארכיאולוגיה

1.  @ilan2018Conquest

2.  @finkelstein2013Forgotten (ch. 1)

## מקרה בוחן: לוחית הקללה מהר עיבל

1.  @stripling2023Cursed

2.  @rollston2023Ebal

3.  @haughwout2024Ebal

## רמות ההר בראשית תקופת הברזל

1.  @faust2016Israel

2.  @dyvvr1998Gzr

3.  @agranat-tamir2020Genomic

## מסע שישק

1.  @finkelstein2013Forgotten (ch. 2)

2.  @nmn1998Ms

## ירושלים וסביבותיה בברונזה המאוחרת ובברזל

1.  @pynqlshtyyn2006Dvd
2.  @mazar2006Jerusalem

3.  @regev2024Radiocarbon

4.  @finkelstein2024Observations

## תקופת השופטים – מקרא וארכיאולוגיה

1.  @master2018Phases

2.  @finkelstein2017Major

3.  @sergi2023Two, מבוא

4.  @rollston2021Jerubbaal

## סיכום – ביקורת המקורות

1.  @ben-yosef2023False

2.  @finkelstein2019First

3.  @dever1995Will

4.  @dever1995Willa

5.  @ben-yosef2021Rethinking

6.  @sukenik2021Purple
